# -*- coding: utf-8 -*-
"""show_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/143ycKViPpY3BvP22cGsm9-Ahu0EAj1WL
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_impulse_response(filename, title):
    h = np.loadtxt(filename)
    plt.figure()
    plt.stem(h, basefmt='b-')
    plt.title(title)
    plt.xlabel('Sample Index')
    plt.ylabel('Amplitude')
    plt.grid(True)
    plt.show()

def plot_log_spectrum(filename, title):
    log_spectrum = np.loadtxt(filename)
    plt.figure()
    plt.plot(log_spectrum)
    plt.title(title)
    plt.xlabel('Sample Index')
    plt.ylabel('Log Spectrum (dB)')
    plt.grid(True)
    plt.show()

def main():
    # Replace these filenames with your actual filenames
    hL_filename = 'hL.txt'
    hR_filename = 'hR.txt'
    YL_filename = 'YL.txt'
    YR_filename = 'YR.txt'

    plot_impulse_response(hL_filename, 'Impulse Response (Left Channel)')
    plot_impulse_response(hR_filename, 'Impulse Response (Right Channel)')

    plot_log_spectrum(YL_filename, 'Log Spectrum (Left Channel)')
    plot_log_spectrum(YR_filename, 'Log Spectrum (Right Channel)')

if __name__ == "__main__":
    main()